### ISSUE TITLE
Upgrade logback_classic and slf4j to version to 1.5.6

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/shibboleth-idp5-installer#18]

**Comment by ArthurZheng** [comment]
Hey Terry, just FYI: https://github.com/ausaccessfed/rapid-idp/issues/1452#issuecomment-2262141566
/opt/idp/jetty/lib/logging/slf4j-api-2.0.6.jar
/opt/idp/jetty/lib/logging/logback-classic-1.5.6.jar
/opt/idp/jetty/lib/logging/logback-core-1.5.6.jar
/opt/idp/shibboleth-src/shibboleth-identity-provider-5.1.3/webapp/WEB-INF/lib/slf4j-api-2.0.13.jar

**Comment by trsau** [comment]
Upgrade the following jars that are used by the installer:

- jcl-over-slf4j-2.0.16.jar
- logback-classic-1.5.7.jar
- logback-core-1.5.7.jar
- spring-jdbc-6.1.12.jar
